### PR TITLE
Log errors when sending voice data

### PR DESCRIPTION
**Pull request by notkaip**

### CODE REVIEW

**Comment by suicvne** [comment]
`VoiceDebugLogger.Log` instead of `GetDebugLogger.Log`. `GetDebugLogger.Log` is incorrect anyway because it's a method. it would have to be `GetDebugLogger().Log`

**Comment by notkaip** [comment]
`GetDebugLogger` is not a method.

**Comment by suicvne** [comment]
My bad `GetDebugLogger` is in the text client. Just do `VoiceDebugLogger.Log`

**Comment by notkaip** [comment]
`GetDebugLogger` is also in the voice client, it just returns `VoiceDebugLogger`. I will change it though, despite the fact that the compiler should just optimize it away anyways.

**Pull request merged**
